version: "3.8"

services: 
  postgres:
    container_name: postgres
    image: postgres:15
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourStrongPassword12#
      - POSTGRES_DB=taskboard
    volumes: 
      - pgdata:/var/lib/postgresql/data
    restart: always

  web-app:
    container_name: web-app
    build:
      context: ./TaskBoard.WebApp
      dockerfile: Dockerfile
    ports: 
      - "5000:80"
    restart: on-failure
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=taskboard
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=yourStrongPassword12#
    depends_on:
      - postgres

volumes:
  pgdata:
